DELETE FROM administrativo.bem;
DELETE FROM administrativo.bem_produto;
DELETE FROM administrativo.cargo;
DELETE FROM administrativo.categoria;
DELETE FROM administrativo.pessoa;
DELETE FROM administrativo.cliente;
DELETE FROM administrativo.cliente_imovel;
DELETE FROM administrativo.comodo;
DELETE FROM administrativo.departamento;
DELETE FROM administrativo.departamento_cargo;
DELETE FROM administrativo.estoque;
DELETE FROM administrativo.fornecedor;
DELETE FROM administrativo.fornecedor_categoria;
DELETE FROM administrativo.funcionario;
DELETE FROM administrativo.imovel;
DELETE FROM administrativo.imovel_comodo;
DELETE FROM administrativo.item_pedido_compra;
DELETE FROM administrativo.item_pedido_venda;
DELETE FROM administrativo.movimentacao;
DELETE FROM administrativo.pedido_compra;
DELETE FROM administrativo.pedido_venda;
DELETE FROM administrativo.produto;
DELETE FROM administrativo.produto_fornecedor;
DELETE FROM administrativo.sub_categoria;
DELETE FROM administrativo.acao_bem;
DELETE FROM administrativo.porta_arduino;


ALTER SEQUENCE administrativo.acao_bem_id_acao_bem_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.bem_id_bem_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.bem_produto_id_bem_produto_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.cargo_id_cargo_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.categoria_id_categoria_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.cliente_id_cliente_seq RESTART WITH 1;
--ALTER SEQUENCE administrativo.movimentacao_id_movimentacao_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.cliente_imovel_id_cliente_imovel_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.comodo_id_comodo_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.departamento_cargo_id_departamento_cargo_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.departamento_id_departamento_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.estoque_id_estoque_seq RESTART WITH 1;
--ALTER SEQUENCE administrativo.estoque_id_estoque_seq1 RESTART WITH 1;
ALTER SEQUENCE administrativo.fornecedor_categoria_id_fornecedor_categoria_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.fornecedor_id_fornecedor_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.funcionario_id_funcionario_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.imovel_comodo_id_imovel_comodo_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.imovel_id_imovel_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.item_pedido_compra_id_item_pedido_compra_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.item_pedido_venda_id_item_pedido_venda_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.pedido_compra_id_pedido_compra_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.pedido_venda_id_pedido_venda_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.pessoa_id_pessoa_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.produto_fornecedor_id_produto_fornecedor_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.produto_id_produto_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.sub_categoria_id_sub_categoria_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.arduino_venda_id_arduino_seq RESTART WITH 1;
ALTER SEQUENCE administrativo.porta_arduino_id_porta_arduino_seq RESTART WITH 1;



ALTER SEQUENCE administrativo.porta_arduino_id_porta_arduino_seq START WITH 1;
ALTER SEQUENCE administrativo.arduino_venda_id_arduino_seq START WITH 1;
ALTER SEQUENCE administrativo.acao_bem_id_acao_bem_seq START WITH 1;
ALTER SEQUENCE administrativo.bem_id_bem_seq START WITH 1;
ALTER SEQUENCE administrativo.bem_produto_id_bem_produto_seq START WITH 1;
ALTER SEQUENCE administrativo.cargo_id_cargo_seq START WITH 1;
ALTER SEQUENCE administrativo.categoria_id_categoria_seq START WITH 1;
ALTER SEQUENCE administrativo.cliente_id_cliente_seq START WITH 1;
ALTER SEQUENCE administrativo.cliente_imovel_id_cliente_imovel_seq START WITH 1;
ALTER SEQUENCE administrativo.comodo_id_comodo_seq START WITH 1;
ALTER SEQUENCE administrativo.departamento_cargo_id_departamento_cargo_seq START WITH 1;
ALTER SEQUENCE administrativo.departamento_id_departamento_seq START WITH 1;
ALTER SEQUENCE administrativo.estoque_id_estoque_seq START WITH 1;
--ALTER SEQUENCE administrativo.movimentacao_id_movimentacao_seq START WITH 1;
--ALTER SEQUENCE administrativo.estoque_id_estoque_seq1 START WITH 1;
ALTER SEQUENCE administrativo.fornecedor_categoria_id_fornecedor_categoria_seq START WITH 1;
ALTER SEQUENCE administrativo.fornecedor_id_fornecedor_seq START WITH 1;
ALTER SEQUENCE administrativo.funcionario_id_funcionario_seq START WITH 1;
ALTER SEQUENCE administrativo.imovel_comodo_id_imovel_comodo_seq START WITH 1;
ALTER SEQUENCE administrativo.imovel_id_imovel_seq START WITH 1;
ALTER SEQUENCE administrativo.item_pedido_compra_id_item_pedido_compra_seq START WITH 1;
ALTER SEQUENCE administrativo.item_pedido_venda_id_item_pedido_venda_seq START WITH 1;
ALTER SEQUENCE administrativo.pedido_compra_id_pedido_compra_seq START WITH 1;
ALTER SEQUENCE administrativo.pedido_venda_id_pedido_venda_seq START WITH 1;
ALTER SEQUENCE administrativo.pessoa_id_pessoa_seq START WITH 1;
ALTER SEQUENCE administrativo.produto_fornecedor_id_produto_fornecedor_seq START WITH 1;
ALTER SEQUENCE administrativo.produto_id_produto_seq START WITH 1;
ALTER SEQUENCE administrativo.sub_categoria_id_sub_categoria_seq START WITH 1;

DELETE FROM cliente_ee;
DELETE FROM dispositivo_ee;
DELETE FROM cliente_imovel;
DELETE FROM cliente;
DELETE FROM arduino;
DELETE FROM pessoa;
DELETE FROM imovel;

ALTER SEQUENCE arduino_id_arduino_seq RESTART WITH 1;
ALTER SEQUENCE arduino_id_arduino_seq START WITH 1;

ALTER SEQUENCE dispositivo_ee_id_dispositivo_ee_seq RESTART WITH 1;
ALTER SEQUENCE dispositivo_ee_id_dispositivo_ee_seq START WITH 1;
